version: "3.5"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto
      - DATABASE_URL=postgres://admin:password@localhost:5432/crypto?sslmode=disable
      - POSTGRES_HOST_AUTH_METHOD=trust